apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: theertha
        image: 7760509331/kubernets:version1
        resources:
        ports:
        - containerPort: 80
